language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install
  - echo "dependencies installed"

# Scripts to be run such as tests
before_script:
  - echo "tests running"
  - npm test

cache: 
  - npm: false

script:
  - docker --version # print the version for logging
  - docker build -t database-api.
  - docker tag simple-node lucasbrogni/database-api:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/database-api